controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login_check:
    path: /api/login_check

dashboard:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index
